app:
  config:
    keycloak:
      server-url: http://localhost:8080/auth
      realm: javatodev-internet-banking
      clientId: internet-banking-api-client
      client-secret: S9i1xx6zNIYZfPkWangeVGxLyLhr9TTd



