spring:
  application:
    name: internet-banking-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_user_service
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8080/auth
      realm: mufid-internet-banking
      clientId: internet-banking-api-client
      client-secret: YC9aN7TtEeJuVP5QSpNycmGzZ6lRwIgl

      spring:
        security:
          oauth2:
            client:
              provider:
                keycloak:
                  token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
                  authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
                  user-name-attribute: preferred_username
                  user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
                  jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
                  user-info-authentication-method: header
              registration:
                internet-banking-core-client:
                  provider: keycloak
                  client-id: internet-banking-core-client
                  client-secret: YC9aN7TtEeJuVP5QSpNycmGzZ6lRwIgl
                  authorization-grant-type: authorization_code
                  redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
                  scope: openid
            resourceserver:
              jwt:
                jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs












